### ISSUE TITLE
How to use this project on Linux

### ISSUE THREAD

**Issue by lyluojy** [ststeiger/SvgConverter#1]
Hello, thank you for sharing the project. I can use VS2017 compilation on Windows system, which solves my problem. But now I need to use your svgconverter project on Linux, but I don't know how to compile it. I'm considering whether to use cmake. Do you have any good suggestions?

**Comment by ststeiger** [comment]
You can try [JetBrains Rider. ](https://www.jetbrains.com/rider/nextversion/)
You also need to [install the .net SDK](https://docs.microsoft.com/en-us/dotnet/core/install/linux-ubuntu)

Actually, you'll probably need VS2019, 2017 will not work with .NET Core 3.x

**Comment by lyluojy** [comment]
Thank you for your reply. I tried to install JetBrains rider compiler on Linux, but it didn't seem to work because it needed. DLL files, so it couldn't succeed.

**Comment by ststeiger** [comment]
Maybe you should download the Linux-version of rider ;)

**Comment by lyluojy** [comment]
I have installed the Linux-version of rider. However, because libs is required to compile, and all the files in libs are .dll files, these files cannot be used under Linux, so I can not compile this project in the Linux-version of rider.

**Comment by ststeiger** [comment]
@lyluojy:  Sorry, i thought it was another project. 
That's correct, this is a Windows-Only program. 
It uses a library called WoutWare CAD to convert DWG to SVG. 

Luckily for you, there's a NetStandard version of WoutWare (NetStandard = also for .NET Core and Linux). 
https://www.woutware.com/ww.cad.netstandard
Try it with these, the source code should hopefully be compatible. 
You should be able to load the 30days trial-version of that library via nuget. 

If you see anything with ODA native dlls and tlds, don't bother, that doesn't even work on Windows. 
Use WoutWare.

**Comment by lyluojy** [comment]
Thank you for your reply, I tried to use the solution you provided, but still can't solve it, so I have switched to other libraries.

**Comment by ststeiger** [comment]
> I have installed the Linux-version of rider. However, because libs is required to compile, and all the files in libs are .dll files, these files cannot be used under Linux, so I can not compile this project in the Linux-version of rider.

That's strange. 
Have you perhaps not installed the [.NET Core SDK](https://docs.microsoft.com/en-us/dotnet/core/install/linux#ubuntu) ? 

As per [instructions](https://docs.microsoft.com/en-us/dotnet/core/install/linux-ubuntu):
```
wget https://packages.microsoft.com/config/ubuntu/20.04/packages-microsoft-prod.deb -O packages-microsoft-prod.deb
sudo dpkg -i packages-microsoft-prod.deb
sudo apt-get update; \
  sudo apt-get install -y apt-transport-https && \
  sudo apt-get update && \
  sudo apt-get install -y dotnet-sdk-3.1
```

**Comment by lyluojy** [comment]
I do have the net core SDK installed, but I still can't solve it.
